# Generated by Django 2.1.3 on 2018-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=25)),
                ('snippet', models.TextField()),
                ('display_link', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('image_link', models.TextField()),
                ('thumbnail_link', models.TextField()),
                ('formatted_url', models.TextField()),
            ],
        ),
    ]
