# Generated by Django 2.1.3 on 2018-12-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_auto_20181116_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='display_link',
            field=models.CharField(max_length=100),
        ),
    ]
