# Generated by Django 2.1.3 on 2018-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0003_auto_20181204_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='display_link',
            field=models.TextField(),
        ),
    ]
