# Generated by Django 2.1.3 on 2018-12-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0004_auto_20181204_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=20)),
                ('account_key', models.TextField()),
                ('account_secret', models.TextField()),
                ('account_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=10)),
                ('user_last_name', models.CharField(max_length=10)),
                ('user_email', models.TextField()),
                ('user_full_name', models.CharField(max_length=20)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksApp.Account')),
            ],
        ),
    ]
