# Generated by Django 2.1.3 on 2018-12-19 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0005_account_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 6, 54, 35, 871685)),
        ),
    ]
