

export default {
    SET_BOOK_SEARCH_DATA: "SET_BOOK_SEARCH_DATA",
    SET_BOOK_SEARCH_PREFIX: "SET_BOOK_SEARCH_PREFIX",
    SET_SELECTED_BOOKS_DATA: "SET_SELECTED_BOOKS_DATA",
    SET_SEARCH_INDEX: "SET_SEARCH_INDEX",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_INFO_MESSAGE: "SET_INFO_MESSAGE",
    CLEAR_GLOBAL_MESSAGE: "CLEAR_GLOBAL_MESSAGE",
    SET_DROPBOX_AUTHENTICATION_FLAG: "SET_DROPBOX_AUTHENTICATION_FLAG",
    API_HOST: "http://localhost:8000"
}
