

export default {
    SET_BOOK_SEARCH_DATA: "SET_BOOK_SEARCH_DATA",
    SET_BOOK_SEARCH_PREFIX: "SET_BOOK_SEARCH_PREFIX",
    SET_SELECTED_BOOKS_DATA: "SET_SELECTED_BOOKS_DATA",
    API_HOST: "http://localhost:8000"
}
